name: studioflow
description: "A new Flutter project."
publish_to: 'none'

version: 1.4.11+4024

environment:
  sdk: ^3.12.2

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  shared_preferences: ^2.5.5
  sqflite: ^2.4.3
  path: ^1.9.1
  url_launcher: ^6.3.2
  crypto: ^3.0.6
  mobile_scanner: ^7.4.0
  permission_handler: ^12.0.3
  flutter_contacts: ^2.3.0
  share_plus: ^11.1.0
  image_picker: ^1.2.3
  image_cropper: ^12.2.1
  path_provider: ^2.1.6
  image: ^4.9.1
  http: ^1.6.0
  connectivity_plus: ^7.3.1
  flutter_secure_storage: ^10.3.1
  flutter_localizations:
    sdk: flutter
  file_picker: ^11.0.3
  pdfx: ^2.9.2
  in_app_purchase: ^3.3.0
  in_app_purchase_android: ^0.5.2
  google_mlkit_text_recognition: ^0.16.0
  qr_flutter: ^4.1.0
  uuid: ^4.6.0

  sqflite_common: any
  intl: any
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  sqflite_common_ffi: ^2.3.6
  flutter_launcher_icons: ^0.14.4
  flutter_native_splash: ^2.4.8

flutter:
  uses-material-design: true

flutter_launcher_icons:
  android: "ic_launcher"
  ios: true
  image_path: "assets/branding/studioflow-icon-v6.png"

flutter_native_splash:
  color: "#70569A"
  image: "assets/branding/studioflow-play-icon-512.png"
  android: true
  ios: true
